#!/bin/sh

commit_msg_file=$1
commit_msg=`cat $commit_msg_file`

red='\033[1;91m'
green='\033[1;92m'
reset='\033[0m'

if ! echo "$commit_msg" | grep -E '^(feat|fix|chore|refact|conflict)\((ADM[0-9]+|release|merge)\): .*' >/dev/null ; then
  echo "${red}Aborting commit. Your commit message is invalid.${reset}\n"
  echo "The commit message was:"
  echo "\n${red}$commit_msg${reset}\n"
  echo "It should be in the format:"
  echo "${green}\"feat|fix|chore|refact(ADM##): commit message\",${reset}"
  echo "In case of release related commits the allowed formats are:"
  echo "${green}\"feat|fix|chore|refact(release): commit message\",${reset}"
  echo "In case of merge due to conflicts it should be in the format:"
  echo "${green}\"conflict(merge): commit message\"${reset}"
  echo "\n"
  exit 1
fi
